global:
  scrape_interval:      15s
  evaluation_interval:  15s
  scrape_timeout:       10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
    # - alertmanager:9093

rule_files:
  # - rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'jenkins'
    metrics_path: /prometheus/ 
    static_configs:
    - targets: ['192.168.173.137:8080']

- job_name: json
  metrics_path: /probe
  static_configs:
    - targets:
      - http://localhost:7979/
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:7979 ## Location of the json exporter's real <hostname>:<port>

